#!/usr/bin/env bash

# tip: "." (i.e. source) this file from your profile (.bashrc), e.g. ". ~/ok"

ok() {

# used for colored output
local RED=$'\033[0;31m'
local CYAN=$'\033[0;36m'
local BLUE=$'\033[0;34m'
local NC=$'\033[0m' # No Color

  # if there is a file called .ok...
  if [ -f .ok ]; then
        re='^[0-9]+$'
        # if the user provided a parameter, $1, which contains a number...
        if [[ $1 =~ $re ]] ; then
          # save and remove argument. Remaining arguments are passwed to eval automatically
          LINE_NR=$1
          shift
          # output the command first
          cat .ok | grep -vE "^#" | echo -e "${CYAN}$ ${NC}$(sed $LINE_NR'!d')" | sed -E "s/(#.*)\$/${BLUE}\1${NC}/1"
          # remove commented lines, and execute that line from the file
          eval $( cat .ok | grep -vE "^#" | sed ${LINE_NR}'!d' )
        else
          # list the content of the file, with a number (1-based) before each line,
          # except lines starting with a "#", those are printed red without a number) as headers
          cat .ok | awk -v r=$RED -v z=$CYAN -v b=$BLUE -v n=$NC $'
            $0 ~ /^#/ {
              #print the (sub-)headings
              print r $0 n;
            }
            $0 ~ /^[^#]/ {
              #print the commands
              sub(/#/,b "#");
              print z "" ++i "." n " " $0 n;
            }'
        fi
  fi
}
